//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetail
    {
        public int SaleDetailKey { get; set; }
        public Nullable<int> SaleKey { get; set; }
        public Nullable<int> ProductKey { get; set; }
        public decimal SaleDetailPriceCharged { get; set; }
        public int SaleDetailQuantity { get; set; }
        public Nullable<decimal> SaleDetailDiscount { get; set; }
        public Nullable<decimal> SaleDetailSaleTaxPercent { get; set; }
        public Nullable<decimal> SaleDetailEatInTax { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
